### ISSUE TITLE
腾讯云函数运行使用cf worker反代的url推送时失败

### ISSUE THREAD

**Issue by SleepCC** [JunzhouLiu/BILIBILI-HELPER-PRE#49]
推送配置为 
"pushConfig": {
    "TG_BOT_TOKEN": "https://xxx.xxx.workers.dev/botxxxxxx74:AAEdxxxxxxxxxxxxxxxxkIriIFXEJBxuY",
    "TG_USER_ID": "123",
    "TG_USE_CUSTOM_URL": true
  }

查了一下，可能是证书问题
https://cloud.tencent.com/document/product/583/59024#.E8.AF.81.E4.B9.A6.E9.97.AE.E9.A2.98

日志如下：

2021-09-28 03:48:47.936 INFO  top.misec.config.ConfigLoader main - 云函数配置初始化成功
2021-09-28 03:48:49.395 INFO  top.misec.utils.VersionInfo main - -----版本信息-----
2021-09-28 03:48:49.396 INFO  top.misec.utils.VersionInfo main - 当前版本: 2.0.8
2021-09-28 03:48:49.398 INFO  top.misec.utils.VersionInfo main - 最新版本为: 2.0.8
2021-09-28 03:48:49.399 INFO  top.misec.utils.VersionInfo main - -----最新版本更新内容-----
1. 取消企业微信图文模式截断。
3. 增加gitlab流水线支持。
2. 修复月底充电时间为28号，之前不小心写成8号了。
4. 修复赛事预测执行过程中硬币低于预留值后继续预测的问题。
2021-09-28 03:48:49.399 INFO  top.misec.utils.VersionInfo main - 最近更新时间: "2021-09-24T15:26:29Z"
2021-09-28 03:48:49.407 INFO  top.misec.utils.VersionInfo main - 项目开源地址: https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE
2021-09-28 03:48:49.407 INFO  top.misec.BiliMain main - 已开启了跳过本日任务，（不会发起任何网络请求），如果需要取消跳过，请将skipDailyTask值改为false
2021-09-28 03:48:50.721 ERROR top.misec.utils.HttpUtils main - 
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at top.misec.utils.HttpUtils.doPost(HttpUtils.java:93)
	at top.misec.push.AbstractPush.post(AbstractPush.java:97)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at top.misec.push.AbstractPush.lambda$push2Target$1(AbstractPush.java:85)
	at io.github.itning.retry.strategy.limit.NoAttemptTimeLimit.call(NoAttemptTimeLimit.java:16)
	at io.github.itning.retry.Retryer.call(Retryer.java:165)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)
	at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)
	at top.misec.BiliMain.mainHandler(BiliMain.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at bootstrap.eventInvoke(bootstrap.java:168)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at bootstrap.main(bootstrap.java:246)
		... 40 common frames omitted
2021-09-28 03:48:50.723 ERROR top.misec.push.AbstractPush main - 推送返回失败：null 已尝试：1次
2021-09-28 03:48:52.364 ERROR top.misec.utils.HttpUtils main - 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at top.misec.utils.HttpUtils.doPost(HttpUtils.java:93)
	at top.misec.push.AbstractPush.post(AbstractPush.java:97)
	at io.github.itning.retry.Retryer.call(Retryer.java:165)
	at top.misec.push.AbstractPush.lambda$push2Target$1(AbstractPush.java:85)
	at io.github.itning.retry.strategy.limit.NoAttemptTimeLimit.call(NoAttemptTimeLimit.java:16)
	at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)
	at top.misec.BiliMain.mainHandler(BiliMain.java:73)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bootstrap.eventInvoke(bootstrap.java:168)
	at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)
	at bootstrap.main(bootstrap.java:246)
		... 40 common frames omitted
2021-09-28 03:48:52.365 ERROR top.misec.push.AbstractPush main - 推送返回失败：null 已尝试：2次
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
2021-09-28 03:48:53.948 ERROR top.misec.utils.HttpUtils main - 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at top.misec.utils.HttpUtils.doPost(HttpUtils.java:93)
	at top.misec.push.AbstractPush.post(AbstractPush.java:97)
	at io.github.itning.retry.strategy.limit.NoAttemptTimeLimit.call(NoAttemptTimeLimit.java:16)
	at top.misec.push.AbstractPush.lambda$push2Target$1(AbstractPush.java:85)
	at io.github.itning.retry.Retryer.call(Retryer.java:165)
	at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)
	at top.misec.BiliMain.mainHandler(BiliMain.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at bootstrap.main(bootstrap.java:246)
	at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)
	at bootstrap.eventInvoke(bootstrap.java:168)
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		... 40 common frames omitted
2021-09-28 03:48:53.949 ERROR top.misec.push.AbstractPush main - 重试最终失败：TelegramCustomUrlPush
	at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)
io.github.itning.retry.RetryException: Retrying failed to complete successfully after 3 attempts.
	at io.github.itning.retry.Retryer.call(Retryer.java:175)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)
	at top.misec.BiliMain.mainHandler(BiliMain.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)
	at bootstrap.eventInvoke(bootstrap.java:168)
	at bootstrap.main(bootstrap.java:246)

**Comment by itning** [comment]
@SleepCC 请下载并使用该jar包再试一次：
[https://itning.lanzoui.com/ijMlmumdqof](https://itning.lanzoui.com/ijMlmumdqof)

**Comment by SleepCC** [comment]
测试后还是显示一样的错误

**Comment by itning** [comment]
[https://itning.lanzoui.com/iggIvumfgqj](https://itning.lanzoui.com/iggIvumfgqj)

@SleepCC 是的文档我看了下 请再试下

**Comment by SleepCC** [comment]
仍然不行，错误相同@itning

**Comment by itning** [comment]
> 仍然不行，错误相同@itning

请扫码加入微信群 

![lALPDg7mSEK-K73NBP_NAnI_626_1279](https://user-images.githubusercontent.com/19759891/135074903-ef3cdcdb-0d7d-43b1-a995-ff7167543e41.png)

**Comment by itning** [comment]
![image](https://user-images.githubusercontent.com/19759891/135188931-9775a833-ba55-48f5-a28d-2fd0f782a8dc.png)

**Comment by itning** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/releases/tag/v2.0.10
已尝试修复

![image](https://user-images.githubusercontent.com/19759891/135198096-25e4d857-09fe-47cd-b527-b02a1adcc50a.png)

**Comment by itning** [comment]
已在群中沟通
