### ISSUE TITLE
云函数Telegram推送失败

### ISSUE THREAD

**Issue by wym3253** [JunzhouLiu/BILIBILI-HELPER-PRE#52]
云函数选择的区域为香港，执行日志如下： 

START RequestId:79df060a-869d-4ad3-8547-4d7809e0bd98

2021-09-29 01:06:45.159 INFO  top.misec.config.ConfigLoader main - 云函数配置初始化成功

2021-09-29 01:06:46.047 INFO  top.misec.utils.VersionInfo main - -----版本信息-----

2021-09-29 01:06:46.047 INFO  top.misec.utils.VersionInfo main - 当前版本: 2.0.9

2021-09-29 01:06:46.049 INFO  top.misec.utils.VersionInfo main - 最新版本为: 2.0.9

2021-09-29 01:06:46.050 INFO  top.misec.utils.VersionInfo main - -----最新版本更新内容-----

1. 修复推送乱码。

2021-09-29 01:06:46.050 INFO  top.misec.utils.VersionInfo main - 最近更新时间: "2021-09-28T13:22:16Z"

2021-09-29 01:06:46.061 INFO  top.misec.utils.VersionInfo main - 项目开源地址: https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE

2021-09-29 01:06:47.113 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1K64y1r7Cs投过1枚硬币啦

2021-09-29 01:06:47.148 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1z64y1d76P投过1枚硬币啦

2021-09-29 01:06:47.184 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1Eo4y1Z7bA投过1枚硬币啦

2021-09-29 01:06:47.219 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1eZ4y1p7GZ投过1枚硬币啦

2021-09-29 01:06:47.254 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1qE411s7Xx投过1枚硬币啦

2021-09-29 01:06:47.291 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1PJ411y7T7投过1枚硬币啦

2021-09-29 01:06:47.325 INFO  top.misec.task.CoinAdd main - 之前已经为avBV1px41117ii投过1枚硬币啦

2021-09-29 01:06:47.326 INFO  top.misec.task.UserCheck main - Cookies有效，登录成功

2021-09-29 01:06:47.328 INFO  top.misec.task.UserCheck main - 用户名称:

2021-09-29 01:06:47.329 INFO  top.misec.task.UserCheck main - 硬币余额: 709.0

2021-09-29 01:07:15.416 INFO  top.misec.task.CoinLogs main - 最近一周共计67条硬币记录

2021-09-29 01:07:15.417 INFO  top.misec.task.CoinLogs main - 最近一周收入72.60000000000001个硬币

2021-09-29 01:07:15.417 INFO  top.misec.task.CoinLogs main - 最近一周支出-90.0个硬币

2021-09-29 01:07:39.972 INFO  top.misec.task.GetVipPrivilege main - 非大会员，跳过领取大会员权益

2021-09-29 01:08:06.529 INFO  top.misec.task.CoinAdd main - 已完成设定的投币任务，今日无需再投币了

2021-09-29 01:08:19.394 INFO  top.misec.task.MangaSign main - 完成漫画签到

2021-09-29 01:08:48.388 INFO  top.misec.task.GiveGift main - 当前无即将过期礼物❌

2021-09-29 01:09:02.189 INFO  top.misec.task.ChargeMe main - 普通会员和月度大会员每月不赠送B币券，所以没法给自己充电哦

2021-09-29 01:09:25.834 INFO  top.misec.task.Silver2Coin main - 当前银瓜子余额为:526,不足700,不进行兑换

2021-09-29 01:09:38.027 INFO  top.misec.task.MangaRead main - 本日漫画自动阅读1章节成功！，阅读漫画为：堀与宫村

2021-09-29 01:09:51.284 INFO  top.misec.task.VideoWatch main - 本日观看视频任务已经完成了，不需要再观看视频了

2021-09-29 01:09:51.284 INFO  top.misec.task.DailyTask main - 请求本日任务完成状态成功

2021-09-29 01:09:51.285 INFO  top.misec.task.VideoWatch main - 本日分享视频任务已经完成了，不需要再分享视频了

2021-09-29 01:10:19.489 INFO  top.misec.task.MatchGame main - -----预测开始-----

2021-09-29 01:10:19.489 INFO  top.misec.task.MatchGame main - 2021KPL秋季赛 常规赛 第一轮:西安WE vs 上海RNG.M 的胜者是？

2021-09-29 01:10:19.489 INFO  top.misec.task.MatchGame main - 此问题已经参与过预测了，无需再次预测

2021-09-29 01:10:19.490 INFO  top.misec.task.MatchGame main - -----预测开始-----

2021-09-29 01:10:19.490 INFO  top.misec.task.MatchGame main - 2021KPL秋季赛 常规赛 第一轮:北京WB vs XYG 的胜者是？

2021-09-29 01:10:19.490 INFO  top.misec.task.MatchGame main - 此问题已经参与过预测了，无需再次预测

2021-09-29 01:10:42.950 WARN  top.misec.task.LiveChecking main - 直播签到失败: 今日已签到过,无法重复签到

2021-09-29 01:11:12.207 INFO  top.misec.task.DailyTask main - 本日任务已全部执行完毕

2021-09-29 01:11:12.299 INFO  top.misec.task.TaskInfoHolder main - 今日获得的总经验值为: 65

2021-09-29 01:11:12.300 INFO  top.misec.task.TaskInfoHolder main - 按照当前进度，升级到升级到Lv6还需要: 153天

2021-09-29 01:11:12.699 ERROR top.misec.utils.HttpUtils main - 

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

  at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)

  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)

  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)

  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)

  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)

  at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)

  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)

  at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)

  at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)

  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at top.misec.utils.HttpUtils.doPost(HttpUtils.java:93)

  at top.misec.push.AbstractPush.post(AbstractPush.java:97)

  at io.github.itning.retry.strategy.limit.NoAttemptTimeLimit.call(NoAttemptTimeLimit.java:16)

  at io.github.itning.retry.Retryer.call(Retryer.java:165)

  at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)

  at top.misec.BiliMain.mainHandler(BiliMain.java:70)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)

  at bootstrap.main(bootstrap.java:246)

  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)

  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)

  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)

  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)

  at io.github.itning.retry.strategy.limit.NoAttemptTimeLimit.call(NoAttemptTimeLimit.java:16)

  at io.github.itning.retry.Retryer.call(Retryer.java:165)

  at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)

  at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:81)

  at top.misec.BiliMain.mainHandler(BiliMain.java:70)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at bootstrap.eventInvoke(bootstrap.java:168)

  at bootstrap.main(bootstrap.java:246)

2021-09-29 01:11:14.080 ERROR top.misec.push.AbstractPush main - 推送返回失败：null 已尝试：2次

2021-09-29 01:11:15.464 ERROR top.misec.utils.HttpUtils main - 

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

  at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)

  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)

  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)

  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)

  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)

  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)

  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)

  at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)

  at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)

  at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)

  at top.misec.utils.HttpUtils.doPost(HttpUtils.java:93)

  at top.misec.push.AbstractPush.lambda$push2Target$1(AbstractPush.java:85)

  at top.misec.push.AbstractPush.push2Target(AbstractPush.java:85)

  at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:81)

  at top.misec.BiliMain.mainHandler(BiliMain.java:70)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)

  at bootstrap.main(bootstrap.java:246)

2021-09-29 01:11:15.467 ERROR top.misec.push.AbstractPush main - 重试最终失败：TelegramPush

io.github.itning.retry.RetryException: Retrying failed to complete successfully after 3 attempts.

  at top.misec.push.AbstractPush.doPush(AbstractPush.java:67)

  at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:81)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:230)

  at bootstrap.main(bootstrap.java:246)

Response RequestId:79df060a-869d-4ad3-8547-4d7809e0bd98 RetMsg:null

END RequestId:79df060a-869d-4ad3-8547-4d7809e0bd98

Report RequestId:79df060a-869d-4ad3-8547-4d7809e0bd98 Duration:271611ms Memory:512MB MemUsage:151.894531MB

**Comment by itning** [comment]
#49

**Comment by itning** [comment]
@wym3253 反代地址发下 不用发token

**Comment by wym3253** [comment]
> token

我没有使用反代，以前v1版本时香港地区不需要反代也可以正常推送

**Comment by itning** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/releases/tag/v2.0.10

已尝试修复

![image](https://user-images.githubusercontent.com/19759891/135198027-d26822de-2a51-4924-94af-8c22d89495a5.png)

**Comment by wym3253** [comment]
> 
> 
> [`v2.0.10` (release)](https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/releases/tag/v2.0.10)
> 
> 已尝试修复
> 
> ![image](https://user-images.githubusercontent.com/19759891/135198027-d26822de-2a51-4924-94af-8c22d89495a5.png)

已可以成功推送，谢谢
